### ISSUE TITLE
Support java8

### ISSUE THREAD

**Issue by zsf513** [junghoon-vans/spring-data-meilisearch#68]
Do you have the plan to support java8?

**Comment by junghoon-vans** [comment]
Thank you for your interest in my project. 

The project is currently being developed using [Spring Data Build](https://github.com/spring-projects/spring-data-build). This means that it is being developed against Java 17, and it may be difficult to provide features that work in Java8.

If support for legacy versions of Java is ever made available, it will be after the core logic being developed is fully implemented.

Thanks.
